### ISSUE TITLE
WISARD does not use the pixelsize and field of view of the input image

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/wisard-ci#2]
WISARD reconstruct a 32x32 image whatever is the size of the input image. According to OI-interface the field of view and the sampling should be given only by the input image.

**Comment by GillesDuvert** [comment]
mmh? strange. will look into this.

**Comment by FerreolS** [comment]
To reproduce the bug:
- load an OIfits
- create a image larger than 32x32 using the create image button
- run WISARD with the created image as input

**Comment by GillesDuvert** [comment]
bug not reproducible. wrong (very old?) version of wisard?

**Comment by FerreolS** [comment]
So rebuilding the docker images should be sufficient. 
It is planned. See https://github.com/orgs/JMMC-OpenDev/projects/3#card-72885500

**Comment by bourgesl** [comment]
I tested with an input image of 102x102 (25mas, incr=0.25) and wisard returns an image 64x64:
`Line equivalent of your command: wisardgui,display=0,"/usr/local/tomcat/temp/uws/UPLOAD_1639411514798_inputfile","/usr/local/tomcat/temp/uws/UPLOAD_1639411514798_inputfile.out",target="FKV1137",fluxerr=0.0010000000,nbiter=200,fov=20.0000,np_min=64,regul="L1L2",waverange=[0.54999998,0.54999998],rgl_wgt=0.000100000,delta=1.00000`

**Comment by GillesDuvert** [comment]
cannot reproduce.
Oimaging version 5.4 beta 9,
wisard-local up-to-date with github version.
???

**Comment by bourgesl** [comment]
I tested again after having removed most parameters in the INPUT PARAM table of my test file: it works like a charm !

**Comment by GillesDuvert** [comment]
indeed if input_param still contains np_min then this value supercedes the value  deduced from the input image size.
There will always be cases where WISARD will create an image larger than the input_image, if the input image has too few pixels.
